spring:
  main:
    banner-mode: off
  jpa:
    open-in-view: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  serviceUrl:
    defaultZone: ${eureka.url:http://172.17.0.2:8761/eureka/}
  instance:
    hostname: 172.17.0.2
